// script.js - Variable Matrix Workspace with External JSON Constant Lookup

let m = 5; 
let n = 4; 
let rawData = [];
let wheelerBookCatalog = null;

// Locked case study data from the article
const COATING_BASELINES = [
    [250, 260, 230, 270], // Coating A
    [310, 330, 280, 360], // Coating B
    [250, 230, 220, 260], // Coating C
    [340, 270, 300, 320], // Coating D
    [250, 240, 270, 290]  // Coating E
];

// Asynchronously fetch the JSON catalog generated by the Python parser
async function loadConstantsCatalog() {
    try {
        const response = await fetch('anom_anor_constants.json');
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        wheelerBookCatalog = await response.json();
        console.log("Successfully loaded Wheeler constants catalog.");
        calculateAndRender();
    } catch (error) {
        console.error("Failed to load anom_anor_constants.json. Using fallback parameters.", error);
    }
}

// Direct-key extraction from JSON matrix data structures
function getScalingFactors(currentM, currentN, alpha, type) {
    if (wheelerBookCatalog) {
        const chartTable = wheelerBookCatalog[type];
        const alphaTable = chartTable ? chartTable[alpha] : null;
        const mKey = `m${currentM}`;
        
        if (alphaTable && alphaTable[mKey] && alphaTable[mKey][currentN]) {
            return wheelerBookCatalog[type][alpha][mKey][currentN];
        }
    }
    
    // Strict fallback values if file isn't loaded yet or sizes exceed table boundaries
    return type === 'ANOM' ? 0.540 : 1.991;
}

function syncDimensionsAndRegen() {
    m = parseInt(document.getElementById('input-m').value) || 5;
    n = parseInt(document.getElementById('input-n').value) || 4;
    
    rawData = [];
    for (let i = 0; i < m; i++) {
        let row = [];
        // If within bounds of your sample data, preserve it exactly
        if (i < COATING_BASELINES.length) {
            let originalRow = COATING_BASELINES[i];
            for (let j = 0; j < n; j++) {
                if (j < originalRow.length) {
                    row.push(originalRow[j]);
                } else {
                    // Smooth padding if columns scale out
                    row.push(originalRow[originalRow.length - 1] + (j % 2 === 0 ? 10 : -10));
                }
            }
        } else {
            // Smooth extrapolation if rows scale beyond 5 groups
            let fallbackBase = [260, 290, 240, 310];
            for (let j = 0; j < n; j++) {
                row.push(fallbackBase[j % fallbackBase.length] + (i * 2));
            }
        }
        rawData.push(row);
    }
    
    renderHeaders();
    initTable();
}

function renderHeaders() {
    const thead = document.getElementById('data-table-head');
    if (!thead) return;
    thead.innerHTML = '';
    let tr = document.createElement('tr');
    
    let thGroup = document.createElement('th');
    thGroup.innerText = 'Group';
    tr.appendChild(thGroup);
    
    for (let j = 1; j <= n; j++) {
        let th = document.createElement('th');
        th.innerText = `X${j}`;
        tr.appendChild(th);
    }
    
    let thMean = document.createElement('th');
    thMean.innerHTML = 'Mean (<span style="text-decoration: overline;">X</span>)';
    tr.appendChild(thMean);
    
    let thRange = document.createElement('th');
    thRange.innerText = 'Range (R)';
    tr.appendChild(thRange);
    
    thead.appendChild(tr);
}

function initTable() {
    const tbody = document.getElementById('data-table-body');
    if (!tbody) return;
    tbody.innerHTML = '';
    rawData.forEach((row, gIdx) => {
        let tr = document.createElement('tr');
        let labelTd = document.createElement('td');
        labelTd.innerHTML = `<b>G${gIdx + 1}</b>`;
        tr.appendChild(labelTd);

        row.forEach((val, rIdx) => {
            let td = document.createElement('td');
            let input = document.createElement('input');
            input.type = 'number';
            input.value = val;
            input.oninput = (e) => {
                rawData[gIdx][rIdx] = Number(e.target.value) || 0;
                calculateAndRender();
            };
            td.appendChild(input);
            tr.appendChild(td);
        });

        let meanTd = document.createElement('td');
        meanTd.id = `mean-g${gIdx}`;
        let rangeTd = document.createElement('td');
        rangeTd.id = `range-g${gIdx}`;
        
        tr.appendChild(meanTd);
        tr.appendChild(rangeTd);
        tbody.appendChild(tr);
    });
    calculateAndRender();
}

function calculateAndRender() {
    if (rawData.length === 0) return;
    
    let groupMeans = [];
    let groupRanges = [];
    
    rawData.forEach((row, idx) => {
        let sum = row.reduce((a, b) => a + b, 0);
        let avg = sum / row.length;
        let min = Math.min(...row);
        let max = Math.max(...row);
        let range = max - min;
        
        groupMeans.push(avg);
        groupRanges.push(range);

        let mElement = document.getElementById(`mean-g${idx}`);
        let rElement = document.getElementById(`range-g${idx}`);
        if(mElement) mElement.innerText = avg.toFixed(2);
        if(rElement) rElement.innerText = range;
    });

    let grandMean = groupMeans.reduce((a,b)=>a+b,0) / groupMeans.length;
    let avgRange = groupRanges.reduce((a,b)=>a+b,0) / groupRanges.length;

    document.getElementById('grand-mean-val').innerText = grandMean.toFixed(2);
    document.getElementById('avg-range-val').innerText = avgRange.toFixed(2);

    let anomAlpha = document.querySelector('input[name="anom_alpha"]:checked').value;
    let anorAlpha = document.querySelector('input[name="anor_alpha"]:checked').value;

    let h_alpha = getScalingFactors(m, n, anomAlpha, 'ANOM');
    let D_alpha = getScalingFactors(m, n, anorAlpha, 'ANOR');

    let anor_UDL = D_alpha * avgRange;
    let anom_delta = h_alpha * avgRange;
    let anom_UDL = grandMean + anom_delta;
    let anom_LDL = grandMean - anom_delta;

    document.getElementById('anor-math').innerHTML = 
        `UDL = ANOR<sub>&alpha;</sub> * R̄<br>` +
        `UDL = ${D_alpha.toFixed(3)} * ${avgRange.toFixed(2)} = <b>${anor_UDL.toFixed(2)}</b>`;

    document.getElementById('anom-math').innerHTML = 
        `Limits = X̿ &plusmn; (ANOM<sub>&alpha;</sub> * R̄)<br>` +
        `Limits = ${grandMean.toFixed(2)} &plusmn; (${h_alpha.toFixed(3)} * ${avgRange.toFixed(2)}) = <b>${anom_LDL.toFixed(2)} to ${anom_UDL.toFixed(2)}</b>`;

    let rangeSignal = groupRanges.some(r => r > anor_UDL);
    let meanSignal = groupMeans.some(m => m > anom_UDL || m < anom_LDL);

    let anorAlert = document.getElementById('anor-alert');
    if(rangeSignal) {
        anorAlert.className = "alert-zone alert-danger";
        anorAlert.innerText = "⚠️ SIGNAL DETECTED: Within-group variance is uneven! This inflates R̄ and desensitizes the ANOM limits.";
    } else {
        anorAlert.className = "alert-zone alert-success";
        anorAlert.innerText = "✓ Within-group variance is stable. The baseline R̄ is robust.";
    }

    let anomAlert = document.getElementById('anom-alert');
    if(meanSignal) {
        anomAlert.className = "alert-zone alert-success";
        anomAlert.innerText = "🎯 SIGNAL DETECTED: Significant differences found across treatment means!";
    } else {
        anomAlert.className = "alert-zone alert-neutral";
        anomAlert.innerText = "No significant difference detected among treatment averages.";
    }

    drawChart('anorChart', groupRanges, avgRange, anor_UDL, 0, "Range");
    drawChart('anomChart', groupMeans, grandMean, anom_UDL, anom_LDL, "Mean");
}

function drawChart(canvasId, points, center, udl, ldl, mode) {
    const canvas = document.getElementById(canvasId);
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    
    const dpr = window.devicePixelRatio || 1;
    const rect = canvas.getBoundingClientRect();
    canvas.width = rect.width * dpr;
    canvas.height = rect.height * dpr;
    ctx.scale(dpr, dpr);

    const w = rect.width;
    const h = rect.height;
    ctx.clearRect(0,0, w, h);

    let allValues = [...points, center, udl, ldl];
    let maxVal = Math.max(...allValues) * 1.15;
    let minVal = mode === "Range" ? 0 : Math.min(...allValues) * 0.85;

    function getY(val) {
        return h - 20 - ((val - minVal) / (maxVal - minVal)) * (h - 35);
    }

    function getX(idx) {
        return 40 + (idx / (points.length - 1 || 1)) * (w - 70);
    }

    ctx.lineWidth = 1.5;
    
    ctx.strokeStyle = '#6c757d';
    ctx.setLineDash([5, 3]);
    ctx.beginPath();
    ctx.moveTo(30, getY(center)); ctx.lineTo(w-10, getY(center));
    ctx.stroke();
    ctx.fillStyle = '#6c757d';
    ctx.font = '10px Arial';
    ctx.fillText(mode === "Range" ? "R̄" : "X̿", 10, getY(center) + 3);

    ctx.strokeStyle = '#dc3545';
    ctx.setLineDash([]);
    ctx.beginPath();
    ctx.moveTo(30, getY(udl)); ctx.lineTo(w-10, getY(udl));
    ctx.stroke();
    ctx.fillStyle = '#dc3545';
    ctx.fillText("UDL", 10, getY(udl) + 3);

    if(mode === "Mean") {
        ctx.strokeStyle = '#dc3545';
        ctx.beginPath();
        ctx.moveTo(30, getY(ldl)); ctx.lineTo(w-10, getY(ldl));
        ctx.stroke();
        ctx.fillStyle = '#dc3545';
        ctx.fillText("LDL", 10, getY(ldl) + 3);
    }

    ctx.strokeStyle = '#0d6efd';
    ctx.lineWidth = 2;
    ctx.beginPath();
    points.forEach((pt, idx) => {
        if(idx === 0) ctx.moveTo(getX(idx), getY(pt));
        else ctx.lineTo(getX(idx), getY(pt));
    });
    ctx.stroke();

    points.forEach((pt, idx) => {
        let isOut = pt > udl || (mode === "Mean" && pt < ldl);
        ctx.fillStyle = isOut ? '#dc3545' : '#0d6efd';
        ctx.beginPath();
        ctx.arc(getX(idx), getY(pt), isOut ? 5 : 3.5, 0, Math.PI*2);
        ctx.fill();
        
        ctx.fillStyle = '#212529';
        ctx.font = '9px Arial';
        ctx.fillText(`G${idx+1}`, getX(idx) - 6, h - 4);
    });
}

// Global configurations update bindings
document.getElementById('input-m').addEventListener('change', syncDimensionsAndRegen);
document.getElementById('input-n').addEventListener('change', syncDimensionsAndRegen);
document.querySelectorAll('input[name="anom_alpha"]').forEach(r => r.addEventListener('change', calculateAndRender));
document.querySelectorAll('input[name="anor_alpha"]').forEach(r => r.addEventListener('change', calculateAndRender));
window.addEventListener('resize', calculateAndRender);

// Boostrap sequence
syncDimensionsAndRegen();
loadConstantsCatalog();

// External Clipboard Data Import Engine Configurations
const importModal = document.getElementById('import-modal');
const openImportBtn = document.getElementById('open-import-btn');
const closeImportBtn = document.getElementById('close-import-btn');
const processImportBtn = document.getElementById('process-import-btn');
const pastedRawText = document.getElementById('pasted-raw-text');

// Manage Modal View States
if (openImportBtn) {
    openImportBtn.addEventListener('click', () => {
        pastedRawText.value = '';
        importModal.style.display = 'flex';
    });
}
if (closeImportBtn) {
    closeImportBtn.addEventListener('click', () => {
        importModal.style.display = 'none';
    });
}

// Intercept window clicks to dim backdrop closures safely
window.addEventListener('click', (e) => {
    if (e.target === importModal) {
        importModal.style.display = 'none';
    }
});

// Clipboard Parsing Engine Logic
if (processImportBtn) {
    processImportBtn.addEventListener('click', () => {
        const rawContent = pastedRawText.value.trim();
        if (!rawContent) {
            alert("No text detected. Please paste your spreadsheet data before processing.");
            return;
        }

        const lines = rawContent.split(/\r?\n/);
        let validMetricsCollection = [];

        lines.forEach(line => {
            // Split rows by standard spreadsheet tabs or multiple space sequences
            const tokens = line.trim().split(/\t| {2,}/);
            if (tokens.length === 0) return;

            // Target the last column tokens containing the raw data metrics
            const potentialNumericToken = tokens[tokens.length - 1].trim();
            const isolatedValue = parseFloat(potentialNumericToken);

            // Strip text layout headers and collect pure numeric values
            if (!isNaN(isolatedValue)) {
                validMetricsCollection.push(isolatedValue);
            }
        });

        if (validMetricsCollection.length < 2) {
            alert("Failed to parse numerical metrics. Ensure columns are structured with numbers on the right margin.");
            return;
        }

        // Chunking the array using your layout parameter context (n columns per group)
        let customGrid = [];
        for (let i = 0; i < validMetricsCollection.length; i += n) {
            let chunk = validMetricsCollection.slice(i, i + n);
            
            // Padding strategy: if the final quarter line leaves a matrix row incomplete,
            // pad the empty cells with the final available metric value to preserve variance stability.
            while (chunk.length < n) {
                chunk.push(chunk[chunk.length - 1]);
            }
            customGrid.push(chunk);
        }

        // Dynamically shift global parameter settings to hold the custom parsed data footprint
        m = customGrid.length;
        rawData = customGrid;

        // Update analytical text displays or structural headers if elements exist
        const mLabel = document.getElementById('input-m');
        const nLabel = document.getElementById('input-n');
        if (mLabel) mLabel.value = m;
        if (nLabel) nLabel.value = n;

        // Rebuild DOM and push calculation updates
        renderHeaders();
        initTable();
        
        // Hide overlay safely
        importModal.style.display = 'none';
        console.log(`Successfully mapped matrix from spreadsheet! Processed ${validMetricsCollection.length} points into ${m} groups.`);
    });
}