// script.js - Variable Matrix Workspace with External JSON Constant Lookup

let m = 5; 
let n = 4; 
let rawData = [];
let globalLabels = []; // Dynamic store for extracted spreadsheet row labels
let wheelerBookCatalog = null;

// Locked case study data from the article
const COATING_BASELINES = [
    [250, 260, 230, 270], // Coating A
    [310, 330, 280, 360], // Coating B
    [250, 230, 220, 260], // Coating C
    [340, 270, 300, 320], // Coating D
    [250, 240, 270, 290]  // Coating E
];

// Asynchronously fetch the JSON catalog generated by the Python parser
async function loadConstantsCatalog() {
    try {
        const response = await fetch('anom_anor_constants.json');
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        wheelerBookCatalog = await response.json();
        console.log("Successfully loaded Wheeler constants catalog.");
        calculateAndRender();
    } catch (error) {
        console.error("Failed to load anom_anor_constants.json. Using fallback parameters.", error);
    }
}

// Direct-key extraction from JSON matrix data structures
function getScalingFactors(currentM, currentN, alpha, type) {
    if (wheelerBookCatalog) {
        const chartTable = wheelerBookCatalog[type];
        const alphaKey = alpha; 
        const altAlphaKey = String(parseFloat(alpha) * 100);
        const alphaTable = chartTable ? (chartTable[alphaKey] || chartTable[altAlphaKey]) : null;
        const mKey = `m${currentM}`;
        
        if (alphaTable && alphaTable[mKey] && alphaTable[mKey][currentN]) {
            return alphaTable[mKey][currentN];
        }
    }
    return type === 'ANOM' ? 0.540 : 1.991;
}

function syncDimensionsAndRegen() {
    const mInput = document.getElementById('input-m');
    const nInput = document.getElementById('input-n');
    
    m = mInput ? (parseInt(mInput.value) || 5) : 5;
    n = nInput ? (parseInt(nInput.value) || 4) : 4;
    
    rawData = [];
    globalLabels = [];
    
    for (let i = 0; i < m; i++) {
        globalLabels.push(`G${i + 1}`); // Default dynamic generic labels
        const row = [];
        if (i < COATING_BASELINES.length) {
            const originalRow = COATING_BASELINES[i];
            for (let j = 0; j < n; j++) {
                if (j < originalRow.length) {
                    row.push(originalRow[j]);
                } else {
                    row.push(originalRow[originalRow.length - 1] + (j % 2 === 0 ? 10 : -10));
                }
            }
        } else {
            const fallbackBase = [260, 290, 240, 310];
            for (let j = 0; j < n; j++) {
                row.push(fallbackBase[j % fallbackBase.length] + (i * 2));
            }
        }
        rawData.push(row);
    }
    
    renderHeaders();
    initTable();
}

function renderHeaders() {
    const thead = document.getElementById('data-table-head');
    if (!thead) return;
    thead.innerHTML = '';
    const tr = document.createElement('tr');
    
    const thGroup = document.createElement('th');
    thGroup.innerText = 'Group';
    tr.appendChild(thGroup);
    
    for (let j = 1; j <= n; j++) {
        const th = document.createElement('th');
        th.innerText = `X${j}`;
        tr.appendChild(th);
    }
    
    const thMean = document.createElement('th');
    thMean.innerHTML = 'Mean (<span style="text-decoration: overline;">X</span>)';
    tr.appendChild(thMean);
    
    const thRange = document.createElement('th');
    thRange.innerText = 'Range (R)';
    tr.appendChild(thRange);
    
    thead.appendChild(tr);
}

function initTable() {
    const tbody = document.getElementById('data-table-body');
    if (!tbody) return;
    tbody.innerHTML = '';
    
    rawData.forEach((row, gIdx) => {
        const tr = document.createElement('tr');
        const labelTd = document.createElement('td');
        
        // Render explicit text label if available, otherwise fall back to row sequence
        const currentLabel = globalLabels[gIdx] || `G${gIdx + 1}`;
        labelTd.innerHTML = `<b>${currentLabel}</b>`;
        tr.appendChild(labelTd);

        row.forEach((val, rIdx) => {
            const td = document.createElement('td');
            const input = document.createElement('input');
            input.type = 'number';
            input.value = val;
            input.oninput = (e) => {
                rawData[gIdx][rIdx] = Number(e.target.value) || 0;
                calculateAndRender();
            };
            td.appendChild(input);
            tr.appendChild(td);
        });

        const meanTd = document.createElement('td');
        meanTd.id = `mean-g${gIdx}`;
        const rangeTd = document.createElement('td');
        rangeTd.id = `range-g${gIdx}`;
        
        tr.appendChild(meanTd);
        tr.appendChild(rangeTd);
        tbody.appendChild(tr);
    });
    calculateAndRender();
}

function calculateAndRender() {
    if (rawData.length === 0) return;
    
    const groupMeans = [];
    const groupRanges = [];
    
    rawData.forEach((row, idx) => {
        const sum = row.reduce((a, b) => a + b, 0);
        const avg = sum / row.length;
        const min = Math.min(...row);
        const max = Math.max(...row);
        const range = max - min;
        
        groupMeans.push(avg);
        groupRanges.push(range);

        const mElement = document.getElementById(`mean-g${idx}`);
        const rElement = document.getElementById(`range-g${idx}`);
        if (mElement) mElement.innerText = avg.toFixed(2);
        if (rElement) rElement.innerText = range.toFixed(4);
    });

    const grandMean = groupMeans.reduce((a, b) => a + b, 0) / groupMeans.length;
    const avgRange = groupRanges.reduce((a, b) => a + b, 0) / groupRanges.length;

    document.getElementById('grand-mean-val').innerText = grandMean.toFixed(2);
    document.getElementById('avg-range-val').innerText = avgRange.toFixed(4);

    const anomAlpha = document.querySelector('input[name="anom_alpha"]:checked').value;
    const anorAlpha = document.querySelector('input[name="anor_alpha"]:checked').value;

    const h_alpha = getScalingFactors(m, n, anomAlpha, 'ANOM');
    const D_alpha = getScalingFactors(m, n, anorAlpha, 'ANOR');

    const anor_UDL = D_alpha * avgRange;
    const anom_delta = h_alpha * avgRange;
    const anom_UDL = grandMean + anom_delta;
    const anom_LDL = grandMean - anom_delta;

    document.getElementById('anor-math').innerHTML = 
        `UDL = ANOR<sub>&alpha;</sub> * R̄<br>` +
        `UDL = ${D_alpha.toFixed(3)} * ${avgRange.toFixed(4)} = <b>${anor_UDL.toFixed(4)}</b>`;

    document.getElementById('anom-math').innerHTML = 
        `Limits = X̿ &plusmn; (ANOM<sub>&alpha;</sub> * R̄)<br>` +
        `Limits = ${grandMean.toFixed(2)} &plusmn; (${h_alpha.toFixed(3)} * ${avgRange.toFixed(4)}) = <b>${anom_LDL.toFixed(4)} to ${anom_UDL.toFixed(4)}</b>`;

    const rangeSignal = groupRanges.some(r => r > anor_UDL);
    const meanSignal = groupMeans.some(m => m > anom_UDL || m < anom_LDL);

    const anorAlert = document.getElementById('anor-alert');
    if (rangeSignal) {
        anorAlert.className = "alert-zone alert-danger";
        anorAlert.innerText = "⚠️ SIGNAL DETECTED: Within-group variance is uneven! This inflates R̄ and desensitizes the ANOM limits.";
    } else {
        anorAlert.className = "alert-zone alert-success";
        anorAlert.innerText = "✓ Within-group variance is stable. The baseline R̄ is robust.";
    }

    const anomAlert = document.getElementById('anom-alert');
    if (meanSignal) {
        anomAlert.className = "alert-zone alert-success";
        anomAlert.innerText = "🎯 SIGNAL DETECTED: Significant differences found across treatment means!";
    } else {
        anomAlert.className = "alert-zone alert-neutral";
        anomAlert.innerText = "No significant difference detected among treatment averages.";
    }

    drawChart('anorChart', groupRanges, avgRange, anor_UDL, 0, "Range");
    drawChart('anomChart', groupMeans, grandMean, anom_UDL, anom_LDL, "Mean");
}

function drawChart(canvasId, points, center, udl, ldl, mode) {
    const canvas = document.getElementById(canvasId);
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    
    const dpr = window.devicePixelRatio || 1;
    const rect = canvas.getBoundingClientRect();
    canvas.width = rect.width * dpr;
    canvas.height = rect.height * dpr;
    ctx.scale(dpr, dpr);

    const w = rect.width;
    const h = rect.height;
    ctx.clearRect(0, 0, w, h);

    const allValues = [...points, center, udl];
    if (mode === "Mean") {
        allValues.push(ldl);
    }
    
    let maxVal = Math.max(...allValues);
    let minVal = mode === "Range" ? 0 : Math.min(...allValues);
    
    const span = maxVal - minVal;
    const paddingMultiplier = span === 0 ? 1 : span * 0.15;
    maxVal += paddingMultiplier;
    if (mode === "Mean") {
        minVal -= paddingMultiplier;
    }

    const decimalPlaces = Math.abs(maxVal) < 10 ? 3 : 1;

    // Expand bottom padding room to 45px to comfortably fit skewed text ranges
    const paddingLeft = 55;
    const paddingRight = 35;
    const paddingTop = 15;
    const paddingBottom = 45;

    function getY(val) {
        return h - paddingBottom - ((val - minVal) / ((maxVal - minVal) || 1)) * (h - paddingTop - paddingBottom);
    }

    function getX(idx) {
        return paddingLeft + (idx / (points.length - 1 || 1)) * (w - paddingLeft - paddingRight);
    }

    // --- 1. DRAW Y-AXIS SCALE & TICK MARKS ---
    ctx.lineWidth = 1;
    ctx.strokeStyle = '#212529';
    ctx.fillStyle = '#212529';
    ctx.font = '10px Arial';
    ctx.textAlign = 'right';
    ctx.textBaseline = 'middle';

    ctx.beginPath();
    ctx.moveTo(paddingLeft, paddingTop);
    ctx.lineTo(paddingLeft, h - paddingBottom);
    ctx.stroke();

    const tickCount = 4;
    for (let i = 0; i <= tickCount; i++) {
        const tickVal = minVal + (i / tickCount) * (maxVal - minVal);
        const yPos = getY(tickVal);
        ctx.beginPath();
        ctx.moveTo(paddingLeft - 4, yPos);
        ctx.lineTo(paddingLeft, yPos);
        ctx.stroke();
        ctx.fillText(tickVal.toFixed(decimalPlaces), paddingLeft - 8, yPos);
    }

    // --- 2. DRAW STATISTICAL BENCHMARKS ---
    ctx.lineWidth = 1.5;
    ctx.textAlign = 'left';
    
    ctx.strokeStyle = '#6c757d';
    ctx.setLineDash([5, 3]);
    ctx.beginPath();
    ctx.moveTo(paddingLeft, getY(center)); 
    ctx.lineTo(w - paddingRight, getY(center));
    ctx.stroke();
    ctx.fillStyle = '#6c757d';
    ctx.fillText(mode === "Range" ? " R̄" : " X̿", w - paddingRight, getY(center));

    ctx.strokeStyle = '#dc3545';
    ctx.setLineDash([]);
    ctx.beginPath();
    ctx.moveTo(paddingLeft, getY(udl)); 
    ctx.lineTo(w - paddingRight, getY(udl));
    ctx.stroke();
    ctx.fillStyle = '#dc3545';
    ctx.fillText(" UDL", w - paddingRight, getY(udl));

    if (mode === "Mean") {
        ctx.strokeStyle = '#dc3545';
        ctx.beginPath();
        ctx.moveTo(paddingLeft, getY(ldl)); 
        ctx.lineTo(w - paddingRight, getY(ldl));
        ctx.stroke();
        ctx.fillStyle = '#dc3545';
        ctx.fillText(" LDL", w - paddingRight, getY(ldl));
    }

    // --- 3. PLOT SERIES TRENDLINE & DATA NODES ---
    ctx.strokeStyle = '#0d6efd';
    ctx.lineWidth = 2;
    ctx.setLineDash([]);
    ctx.beginPath();
    points.forEach((pt, idx) => {
        if (idx === 0) ctx.moveTo(getX(idx), getY(pt));
        else ctx.lineTo(getX(idx), getY(pt));
    });
    ctx.stroke();

    points.forEach((pt, idx) => {
        const isOut = pt > udl || (mode === "Mean" && pt < ldl);
        ctx.fillStyle = isOut ? '#dc3545' : '#0d6efd';
        ctx.beginPath();
        ctx.arc(getX(idx), getY(pt), isOut ? 5 : 3.5, 0, Math.PI * 2);
        ctx.fill();
        
        // --- 4. RENDER ROTATED X-AXIS LABELS ---
        ctx.save();
        const labelX = getX(idx);
        const labelY = h - paddingBottom + 8;
        
        // Translate transformations origin straight to the tick mark coordinate point
        ctx.translate(labelX, labelY);
        ctx.rotate((45 * Math.PI) / 180); // Rotate 45° clockwise
        
        ctx.fillStyle = '#212529';
        ctx.font = '9px Arial';
        ctx.textAlign = 'left';
        ctx.textBaseline = 'middle';
        
        const currentLabel = globalLabels[idx] || `G${idx + 1}`;
        ctx.fillText(currentLabel, 0, 0);
        ctx.restore();
    });
}

// Global configurations update bindings
document.getElementById('input-m').addEventListener('change', syncDimensionsAndRegen);
document.getElementById('input-n').addEventListener('change', syncDimensionsAndRegen);
document.querySelectorAll('input[name="anom_alpha"]').forEach(r => r.addEventListener('change', calculateAndRender));
document.querySelectorAll('input[name="anor_alpha"]').forEach(r => r.addEventListener('change', calculateAndRender));
window.addEventListener('resize', calculateAndRender);

// Clipboard Data Import Logic
const importModal = document.getElementById('import-modal');
const openImportBtn = document.getElementById('open-import-btn');
const closeImportBtn = document.getElementById('close-import-btn');
const processImportBtn = document.getElementById('process-import-btn');
const pastedRawText = document.getElementById('pasted-raw-text');

if (openImportBtn) {
    openImportBtn.addEventListener('click', () => {
        pastedRawText.value = '';
        importModal.style.display = 'flex';
    });
}
if (closeImportBtn) {
    closeImportBtn.addEventListener('click', () => {
        importModal.style.display = 'none';
    });
}
window.addEventListener('click', (e) => {
    if (e.target === importModal) {
        importModal.style.display = 'none';
    }
});

if (processImportBtn) {
    processImportBtn.addEventListener('click', () => {
        const rawContent = pastedRawText.value.trim();
        if (!rawContent) {
            alert("No text detected. Please paste your spreadsheet data before processing.");
            return;
        }

        const lines = rawContent.split(/\r?\n/);
        const validMetricsCollection = [];
        const parsedLabelsCollection = [];

        lines.forEach(line => {
            const tokens = line.trim().split(/\t| {2,}/);
            if (tokens.length === 0 || line.trim() === "") return;

            if (tokens.length >= 2) {
                // Two-column layout detected: Extract Column 1 as name label, Column 2 as quantitative metric
                const labelToken = tokens[0].trim();
                const numericToken = tokens[tokens.length - 1].trim();
                const isolatedValue = parseFloat(numericToken);

                if (!isNaN(isolatedValue)) {
                    validMetricsCollection.push(isolatedValue);
                    parsedLabelsCollection.push(labelToken);
                }
            } else if (tokens.length === 1) {
                // Single column continuous metric layout fallback
                const isolatedValue = parseFloat(tokens[0].trim());
                if (!isNaN(isolatedValue)) {
                    validMetricsCollection.push(isolatedValue);
                }
            }
        });

        if (validMetricsCollection.length < 2) {
            alert("Failed to parse numerical metrics. Ensure columns are structured with numbers on the right margin.");
            return;
        }

        // Partition numbers into subgroups based on workspace sizing parameter (n)
        const customGrid = [];
        const dynamicGroupLabels = [];
        
        for (let i = 0; i < validMetricsCollection.length; i += n) {
            const chunk = validMetricsCollection.slice(i, i + n);
            while (chunk.length < n) {
                chunk.push(chunk[chunk.length - 1]);
            }
            customGrid.push(chunk);

            // Assign label configuration: Use the first row cell's label descriptor
            // or fall back to generic index strings if labels are empty
            if (parsedLabelsCollection.length > i) {
                dynamicGroupLabels.push(parsedLabelsCollection[i]);
            } else {
                dynamicGroupLabels.push(`G${customGrid.length}`);
            }
        }

        m = customGrid.length;
        rawData = customGrid;
        globalLabels = dynamicGroupLabels;

        const mLabel = document.getElementById('input-m');
        const nLabel = document.getElementById('input-n');
        if (mLabel) mLabel.value = m;
        if (nLabel) nLabel.value = n;

        renderHeaders();
        initTable();
        
        importModal.style.display = 'none';
        console.log(`Successfully mapped matrix with labels! Processed ${validMetricsCollection.length} points into ${m} groups.`);
    });
}

// Bootstrap initialization sequence
syncDimensionsAndRegen();
loadConstantsCatalog();